version: '2.4'

services:

  db-nest:
    container_name: mongo
    image: mongo:latest
    environment:
      - "MONGO_INITDB_ROOT_USERNAME=root"
      - "MONGO_INITDB_ROOT_PASSWORD=rootpassword"
    volumes:
      - type: volume
        source: nestvolume
        target: /data/db
    ports:
      - "27017:27017"

  rabbit1:
    image: rabbitmq:3-management
    hostname: rabbit1
    environment:
      - ERLANG_COOKIE=abcdefg
      - RABBITMQ_DEFAULT_USER=test
      - RABBITMQ_DEFAULT_PASS=test 
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    image: "redis:alpine"
    command: redis-server --requirepass sOmE_sEcUrE_pAsS
    ports:
      - "6379:6379"
    volumes:
      - $PWD/redis-data:/var/lib/redis
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master


volumes:
  nestvolume:
